parallel:
  data_parallel_size: 2
  fully_shard_parallel_size: 2
  fsdp_plan:
    ignored_modules: []
    apply_modules: ['model.visual', 'model.visual.blocks.{*}', 'model.language_model.embed_tokens', 'model.language_model', 'model.language_model.layers.{*}', 'lm_head', 'mtp']
    param_dtype: bf16
    reduce_dtype: fp32
    output_dtype: None
    cast_forward_inputs: True
    reshard_after_forward: False
    num_to_forward_prefetch: 1
    num_to_backward_prefetch: 1
    pregather: False
    hook_modules: None
    cpu_offload: False
  tensor_parallel_size: 1
  tp_plan:
    colwise_parallel: []
    rowwise_parallel: []
    sequence_parallel: []
  ring_attention_size: 1
  ulysses_parallel_size: 1
  expert_parallel_size: 1
  expert_fully_shard_parallel_size: 1
  ep_plan:
    apply_modules: []
    use_npu_fused_ops: True
    dispatcher: alltoall
    apply_efsdp_modules: []
  recompute: False
  recompute_plan:
    apply_modules: []
    use_reentrant: False
  local_rank: 0
  global_rank: 0
  world_size: 1
model:
  model_id: qwen3_5
  model_name_or_path: /root/Qwen3.5-0.8B-hf
  trust_remote_code: True
  attn_implementation: flash_attention_2
  freeze: ['model.visual']
  mtp_num_layers: 0
  mtp_loss_scaling_factor: 0.1
  gdn_implementation: triton
  causal_conv1d_implementation: triton
  skip_gdn_recompute: True
  skip_flash_attn_recompute: False
data:
  dataset_param:
    dataset_type: huggingface
    basic_parameters:
      cache_dir: ./cache_dir/
      template: qwen3_vl_nothink
      chat_template: None
      enable_thinking: False
      dataset_dir: /root/coco_dl/extracted/dataset
      dataset: ['/root/coco_dl/extracted/dataset/annotations_slim.json']
      cutoff_len: 1024
      train_on_prompt: False
      mask_history: False
      streaming: False
      overwrite_cache: False
      preprocessing_batch_size: 1000
      preprocessing_num_workers: 16
      max_samples: None
      tool_format: None
      val_dataset: None
      val_max_samples: None
      val_rate: None
      packing: None
      neat_packing: False
      preprocess_on_fly: True
      async_preprocess: False
      async_preprocess_buffer_size: None
      stage: sft
    preprocess_parameters:
      model_name_or_path: /root/Qwen3.5-0.8B-hf
      use_fast_tokenizer: True
      split_special_tokens: False
      image_resolution: 512
      video_resolution: 128
      image_max_pixels: 262144
      image_min_pixels: 1024
      video_max_pixels: 16384
      video_min_pixels: 0
      video_fps: 2.0
      video_maxlen: 64
      image_do_pan_and_scan: False
      crop_to_patches: False
      use_audio_in_video: False
      audio_sampling_rate: 16000
      trust_remote_code: False
    attr:
      ranking: False
      system: None
      images: images
      videos: None
      audios: None
      prompt: None
      query: None
      response: None
      history: None
      messages: messages
      tools: None
      role_tag: role
      content_tag: content
      user_tag: user
      assistant_tag: assistant
      observation_tag: observation
      function_tag: function_call
      system_tag: system
      chosen: None
      rejected: None
      formatting: sharegpt
  val_dataset_param: None
  dataloader_param:
    dataloader_mode: sampler
    sampler_type: BaseRandomBatchSampler
    shuffle: False
    drop_last: True
    pin_memory: True
    collate_param:
      collator_id: None
      model_name: qwen3vl
      ignore_pad_token_for_loss: True
      pad_to_multiple_of: 8
    num_workers: 8
    enable_preload: False
training:
  profile:
    enable: False
    start_step: 1
    end_step: 2
    save_path: ./profiling
    record_shapes: True
    with_memory: True
    with_stack: True
    ranks: [0]
    _train_steps: -1
    local_rank: 0
    global_rank: 0
    world_size: 1
    profile_this_rank: False
  lora:
    enable: False
    rank: 8
    alpha: 16
    target_modules: ['q_proj', 'k_proj', 'v_proj']
    dropout: 0.0
    init_lora_weights: True
    pretrained_lora_path: None
    lora_target_modules_support: None
    disable_peft_moe_conversion: True
  lr: 1e-05
  lr_min: 0.0
  lr_start: 0.0
  weight_decay: 0.0
  no_decay_modules: []
  no_decay_params: []
  optimizer: adamw
  mem_fraction_static: 0.8
  matched_adamw_rms: 0.2
  muon_momentum: 0.95
  ns_steps: 5
  adam_fused: True
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 1e-08
  clip_grad: 0.0
  clip_grad_foreach: True
  micro_batch_size: 4
  gradient_accumulation_steps: 1
  lr_warmup_ratio: 0.1
  lr_decay_style: cosine
  lr_decay_ratio: 1.0
  enable_full_determinism: False
  ckpt_manager: dcp
  save_async: False
  save_ckpt_dtype: None
  load_checkpoint_path: None
  save_steps: 0
  seed: 42
  max_steps: None
  init_model_with_meta_device: True
  train_iters: 100
  train_epochs: None
  load: /root/Qwen3.5-0.8B-dcp
  load_format: auto
  save_format: auto
  load_strict: False
  load_rank0_and_broadcast: False
  no_load_optim: True
  no_load_rng: True
  save: ./save_path
  no_save_optim: True
  no_save_rng: True
  log_interval: 1
  save_interval: 10000
  val_interval: 0
  val_micro_batch_size: None
  use_deter_comp: False
  allow_hf32: None
  plugin: ['mindspeed_mm/fsdp/models/qwen3_5', 'mindspeed_mm/fsdp/data/datasets/huggingface']
  lr_scaling_plan: None
  quantization_plan: QuantizeConfig(recipe_name=None, apply_modules=[], ignored_modules=[], quant_converters=[], extra_args={}, enable_fsdp_low_precision_all_gather=True, fsdp_low_precision_all_gather_mode='on-demand')
  _train_steps: -1
  local_rank: 0
  global_rank: 0
  world_size: 1
  global_batch_size: 8
tools:
  profile:
    enable: False
    profile_type: static
    ranks: [0]
    static_param:
      level: level1
      with_stack: False
      with_memory: False
      record_shapes: False
      with_cpu: True
      save_path: ./profiling
      start_step: 10
      end_step: 11
      data_simplification: False
      aic_metrics_type: PipeUtilization
      analyse_flag: True
  memory_profile:
    enable: False
    start_step: 1
    end_step: 2
    save_path: ./memory_snapshot
    dump_ranks: [0]
    stacks: all
    max_entries: None
    mem_info: False
features:
  recompute_plan:
    apply_modules: ['model.visual.blocks.{*}', 'model.language_model.layers.{*}']
    use_reentrant: False
  loss_cfg:
    loss_type: default
    router_aux_loss_coef: 0.0
    router_aux_loss_offload: False
  enable_chunk_loss: True
  enable_dynamic_chunk_loss: False
  chunkloss_plan:
    apply_module: lm_head
    chunk_size: 1024
    total_chunk_size: 4096
  enable_activation_offload: True
  activation_offload_plan:
    apply_modules: ['model.visual.blocks.{*}', 'model.language_model.layers.{*}']
  enable_chunk_mbs: False
  chunkmbs_plan:
    apply_modules: ['model.language_model.layers.{*}']
    chunk_mbs: 2
    batch_dim: 0
    chunk_arg_indexs: [0]
    chunk_kwarg_names: ['position_embeddings', 'position_ids', 'rope_deltas', 'attention_mask']
  enable_ep_balance: False
  ep_balance_plan:
    max_dup_experts_num: 2
  skip_moe_pad_tokens: False
  recompute: True
data.dataset_param.preprocess_parameters.model_name_or_path: /root/Qwen3.5-0.8B-hf
data.dataset_param.preprocess_parameters.use_fast_tokenizer: True
data.dataset_param.preprocess_parameters.split_special_tokens: False
data.dataset_param.preprocess_parameters.image_max_pixels: 262144
data.dataset_param.preprocess_parameters.image_min_pixels: 1024
data.dataset_param.preprocess_parameters.video_max_pixels: 16384
data.dataset_param.preprocess_parameters.video_min_pixels: 0
data.dataset_param.preprocess_parameters.video_fps: 2.0
data.dataset_param.preprocess_parameters.video_maxlen: 64


